name: Docker Image

on:
  workflow_run:
    workflows: ["Check Build"]
    types:
      - completed

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master'}}

    steps:
      - uses: actions/checkout@v2
      - name: Cargo Cache
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo

      - name: Cargo Target Cache
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - uses: actions/checkout@v3
      - name: Build and push the Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: "xp-bot/Dockerfile"
          directory: "xp-bot"
          image: raeys-v8
          tags: latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
